/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/main.ts
__export(exports, {
  default: () => ToolkitPlugin
});
var import_obsidian = __toModule(require("obsidian"));
var DEFAULT_SETTINGS = {
  isHidden: true,
  autoOpenWolaiFolders: true,
  showQuickCreateButton: true,
  showQuickCreateFolderButton: true,
  lockDragAndDrop: false
};
var ToolkitPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.lockRibbonEl = null;
  }
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.addRibbonIcon("image-off", "Toggle Image Folders", (evt) => {
        this.toggleVisibility();
      });
      this.lockRibbonEl = this.addRibbonIcon(this.settings.lockDragAndDrop ? "lock" : "unlock", "Toggle Drag-and-Drop Lock", (evt) => {
        this.toggleDragLock();
      });
      this.refreshDragLock();
      this.addCommand({
        id: "toggle-image-folder-visibility",
        name: "Toggle Image Folder Visibility",
        callback: () => {
          this.toggleVisibility();
        }
      });
      this.addCommand({
        id: "toggle-drag-lock",
        name: "Toggle File Explorer Drag-and-Drop Lock",
        callback: () => {
          this.toggleDragLock();
        }
      });
      this.registerDomEvent(document, "dragstart", (evt) => {
        if (this.settings.lockDragAndDrop) {
          const target = evt.target;
          if (target.closest(".nav-file") || target.closest(".nav-folder")) {
            evt.preventDefault();
            new import_obsidian.Notice("File drag-and-drop is locked by ToolkitPlugin.");
          }
        }
      }, true);
      this.addSettingTab(new ToolkitPluginSettingTab(this.app, this));
      this.refreshVisibility();
      this.registerDomEvent(document, "click", (evt) => {
        if (!this.settings.autoOpenWolaiFolders)
          return;
        const target = evt.target;
        if (target.closest(".toolkit-icons-container") || target.closest(".toolkit-action-icon"))
          return;
        if (target.classList.contains("nav-folder-collapse-indicator") || target.closest(".nav-folder-collapse-indicator")) {
          return;
        }
        const folderTitleEl = target.closest(".nav-folder-title");
        if (folderTitleEl) {
          const path = folderTitleEl.getAttr("data-path");
          if (!path)
            return;
          const folder = this.app.vault.getAbstractFileByPath(path);
          if (folder instanceof import_obsidian.TFolder) {
            this.handleFolderClick(folder);
          }
        }
      });
      this.registerInterval(window.setInterval(() => this.injectCreateButtons(), 1e3));
    });
  }
  injectCreateButtons() {
    if (!this.settings.showQuickCreateButton && !this.settings.showQuickCreateFolderButton)
      return;
    const folderTitles = document.querySelectorAll(".nav-folder-title:not(.has-toolkit-icons)");
    folderTitles.forEach((el) => {
      const folderTitleEl = el;
      folderTitleEl.addClass("has-toolkit-icons");
      const container = folderTitleEl.createEl("div", { cls: "toolkit-icons-container" });
      if (this.settings.showQuickCreateFolderButton) {
        const folderIconContainer = container.createEl("div", { cls: "toolkit-action-icon toolkit-folder-icon" });
        (0, import_obsidian.setIcon)(folderIconContainer, "folder-plus");
        folderIconContainer.setAttr("aria-label", "New folder");
        this.attachCreateListener(folderIconContainer, folderTitleEl, "folder");
      }
      if (this.settings.showQuickCreateButton) {
        const noteIconContainer = container.createEl("div", { cls: "toolkit-action-icon toolkit-note-icon" });
        (0, import_obsidian.setIcon)(noteIconContainer, "plus-with-circle");
        noteIconContainer.setAttr("aria-label", "New note");
        this.attachCreateListener(noteIconContainer, folderTitleEl, "note");
      }
    });
  }
  attachCreateListener(iconEl, folderTitleEl, type) {
    ["mousedown", "mouseup", "click", "pointerdown", "pointerup"].forEach((eventType) => {
      iconEl.addEventListener(eventType, (evt) => {
        evt.stopPropagation();
        evt.stopImmediatePropagation();
        if (eventType === "mousedown" || eventType === "click")
          evt.preventDefault();
        if (eventType === "mousedown" && evt.button === 0) {
          const path = folderTitleEl.getAttr("data-path");
          if (path) {
            const folder = this.app.vault.getAbstractFileByPath(path);
            if (folder instanceof import_obsidian.TFolder) {
              if (type === "note") {
                this.handleQuickCreate(folder, path);
              } else {
                this.handleQuickCreateFolder(folder, path);
              }
            }
          }
        }
      }, true);
    });
  }
  handleQuickCreate(folder, path) {
    return __async(this, null, function* () {
      const appAny = this.app;
      try {
        const explorerLeaves = this.app.workspace.getLeavesOfType("file-explorer");
        explorerLeaves.forEach((leaf) => {
          const view = leaf.view;
          if (view.fileItems && view.fileItems[path]) {
            view.fileItems[path].setCollapsed(false);
          }
        });
        const fileManagerAny = this.app.fileManager;
        let newFile;
        if (typeof fileManagerAny.createNewMarkdownFile === "function") {
          newFile = yield fileManagerAny.createNewMarkdownFile(folder);
        } else {
          newFile = yield this.app.vault.create(`${path}/Untitled.md`, "");
        }
        if (newFile) {
          yield this.app.workspace.getLeaf(false).openFile(newFile);
          explorerLeaves.forEach((leaf) => {
            if (leaf.view.revealFile) {
              leaf.view.revealFile(newFile);
            }
          });
        }
      } catch (e) {
        console.error("toolkitPlusin: Quick create failed", e);
      }
    });
  }
  handleQuickCreateFolder(folder, path) {
    return __async(this, null, function* () {
      try {
        const explorerLeaves = this.app.workspace.getLeavesOfType("file-explorer");
        explorerLeaves.forEach((leaf) => {
          const view = leaf.view;
          if (view.fileItems && view.fileItems[path]) {
            view.fileItems[path].setCollapsed(false);
          }
        });
        let newFolderName = "\u672A\u547D\u540D";
        let counter = 1;
        let newFolderPath = `${path}/${newFolderName}`;
        while (this.app.vault.getAbstractFileByPath(newFolderPath)) {
          newFolderName = `\u672A\u547D\u540D ${counter}`;
          newFolderPath = `${path}/${newFolderName}`;
          counter++;
        }
        const newFolder = yield this.app.vault.createFolder(newFolderPath);
        if (newFolder) {
          setTimeout(() => {
            explorerLeaves.forEach((leaf) => {
              const view = leaf.view;
              if (view.revealFile) {
                view.revealFile(newFolder).then(() => {
                  if (view.fileItems && view.fileItems[newFolderPath]) {
                    const folderItem = view.fileItems[newFolderPath];
                    if (folderItem.setRename) {
                      folderItem.setRename(true);
                    } else {
                      const titleEl = folderItem.titleInnerEl;
                      if (titleEl) {
                        const evt = new MouseEvent("click", { detail: 1 });
                        titleEl.dispatchEvent(evt);
                      }
                    }
                  }
                });
              }
            });
          }, 100);
        }
      } catch (e) {
        console.error("toolkitPlusin: Quick create folder failed", e);
      }
    });
  }
  handleFolderClick(folder) {
    return __async(this, null, function* () {
      const children = folder.children.filter((child) => {
        if (child instanceof import_obsidian.TFolder && child.name.toLowerCase() === "image")
          return false;
        return true;
      });
      const mdFiles = children.filter((child) => child instanceof import_obsidian.TFile && child.extension === "md");
      if (mdFiles.length === 1) {
        const file = mdFiles[0];
        const leaf = this.app.workspace.getLeaf(false);
        leaf.openFile(file);
      }
    });
  }
  toggleDragLock() {
    return __async(this, null, function* () {
      this.settings.lockDragAndDrop = !this.settings.lockDragAndDrop;
      yield this.saveSettings();
      this.refreshDragLock();
      const status = this.settings.lockDragAndDrop ? "Locked" : "Unlocked";
      new import_obsidian.Notice(`File drag-and-drop is now ${status}`);
    });
  }
  refreshDragLock() {
    if (this.lockRibbonEl) {
      (0, import_obsidian.setIcon)(this.lockRibbonEl, this.settings.lockDragAndDrop ? "lock" : "unlock");
    }
    if (this.settings.lockDragAndDrop) {
      document.body.classList.add("is-drag-locked");
    } else {
      document.body.classList.remove("is-drag-locked");
    }
  }
  toggleVisibility() {
    return __async(this, null, function* () {
      this.settings.isHidden = !this.settings.isHidden;
      yield this.saveSettings();
      this.refreshVisibility();
      const status = this.settings.isHidden ? "Hidden" : "Visible";
      new import_obsidian.Notice(`Image folders are now ${status}`);
    });
  }
  refreshVisibility() {
    if (this.settings.isHidden) {
      document.body.classList.add("hide-image-folder");
    } else {
      document.body.classList.remove("hide-image-folder");
    }
  }
  onunload() {
    document.body.classList.remove("hide-image-folder", "is-drag-locked");
    document.querySelectorAll(".toolkit-icons-container").forEach((el) => el.remove());
    document.querySelectorAll(".has-toolkit-icons").forEach((el) => el.classList.remove("has-toolkit-icons"));
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, yield this.loadData());
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
};
var ToolkitPluginSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "ToolkitPlugin Settings" });
    new import_obsidian.Setting(containerEl).setName("Hide Image Folders").setDesc('Hide all folders named "image" in the file explorer.').addToggle((toggle) => toggle.setValue(this.plugin.settings.isHidden).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.isHidden = value;
      yield this.plugin.saveSettings();
      this.plugin.refreshVisibility();
    })));
    new import_obsidian.Setting(containerEl).setName("Auto-open Wolai-style Folders").setDesc("When clicking a folder containing only one MD file with the same name, open the file automatically.").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoOpenWolaiFolders).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.autoOpenWolaiFolders = value;
      yield this.plugin.saveSettings();
    })));
    new import_obsidian.Setting(containerEl).setName("Show Quick Create Button").setDesc('Show a "+" icon on folders to quickly create a new note.').addToggle((toggle) => toggle.setValue(this.plugin.settings.showQuickCreateButton).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.showQuickCreateButton = value;
      yield this.plugin.saveSettings();
      document.querySelectorAll(".toolkit-icons-container").forEach((el) => el.remove());
      document.querySelectorAll(".has-toolkit-icons").forEach((el) => el.classList.remove("has-toolkit-icons"));
      this.plugin.injectCreateButtons();
    })));
    new import_obsidian.Setting(containerEl).setName("Show Quick Create Folder Button").setDesc("Show a folder icon on folders to quickly create a new folder.").addToggle((toggle) => toggle.setValue(this.plugin.settings.showQuickCreateFolderButton).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.showQuickCreateFolderButton = value;
      yield this.plugin.saveSettings();
      document.querySelectorAll(".toolkit-icons-container").forEach((el) => el.remove());
      document.querySelectorAll(".has-toolkit-icons").forEach((el) => el.classList.remove("has-toolkit-icons"));
      this.plugin.injectCreateButtons();
    })));
    new import_obsidian.Setting(containerEl).setName("Lock File Explorer Drag-and-Drop").setDesc("Prevent accidental moving of files and folders in the file explorer.").addToggle((toggle) => toggle.setValue(this.plugin.settings.lockDragAndDrop).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.lockDragAndDrop = value;
      yield this.plugin.saveSettings();
      this.plugin.refreshDragLock();
    })));
  }
};
