/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/main.ts
__export(exports, {
  default: () => ToolkitPlugin
});
var import_obsidian2 = __toModule(require("obsidian"));

// src/i18n/index.ts
var import_obsidian = __toModule(require("obsidian"));

// src/i18n/locales/en.ts
var en_default = {
  HIDE_IMAGE_FOLDERS_NAME: "Hide Image Folders",
  HIDE_IMAGE_FOLDERS_DESC: "Hide folders containing only images to keep the file explorer clean.",
  QUICK_CREATE_FOLDER_NAME: "Show Quick Create Folder Button",
  QUICK_CREATE_FOLDER_DESC: "Add an icon to foldrs for creating subfolders quickly.",
  LOCK_DRAG_NAME: "Lock File Drag and Drop",
  LOCK_DRAG_DESC: "Prevent accidental file/folder movements in the file explorer.",
  SCALE_MERMAID_NAME: "Enable Mermaid Scaling & Zoom",
  SCALE_MERMAID_DESC: "Automatically scale Mermaid diagrams to fit note width and enable hover zoom/fullscreen.",
  MERMAID_SENSITIVITY_NAME: "Mermaid Zoom Sensitivity",
  MERMAID_SENSITIVITY_DESC: "Adjust how fast Mermaid diagrams scale with your wheel/pinch gesture (Default: 1.0).",
  AUTO_OPEN_WOLAI_NAME: "Auto-open Wolai-style Folders",
  AUTO_OPEN_WOLAI_DESC: "When clicking a folder containing only one MD file with the same name, open the file automatically.",
  QUICK_CREATE_NOTE_NAME: "Show Quick Create Button",
  QUICK_CREATE_NOTE_DESC: "Show a '+' icon on folders to quickly create a new note.",
  AUTO_DETECT_LANG_NAME: "Auto-detect Code Language",
  AUTO_DETECT_LANG_DESC: "Automatically detect and fill language tags when pasting code into a blank code block.",
  AUTO_FOCUS_BLOCK_NAME: "Auto-focus in Code Blocks",
  AUTO_FOCUS_BLOCK_DESC: "Automatically move the cursor inside the code block when a new empty block structure is detected.",
  COMMAND_TOGGLE_DRAG: "Toggle File Explorer Drag-and-Drop Lock",
  COMMAND_TOGGLE_IMAGES: "Toggle Image Folder Visibility",
  RIBBON_TOGGLE_IMAGES: "Toggle Image Folders",
  RIBBON_TOGGLE_DRAG: "Toggle Drag-and-Drop Lock",
  MERMAID_ZOOM_IN: "Zoom In",
  MERMAID_ZOOM_OUT: "Zoom Out",
  MERMAID_RESET: "Reset Zoom",
  MERMAID_FULLSCREEN: "Fullscreen",
  MERMAID_MODAL_TITLE: "Mermaid Diagram Viewer",
  NEW_FOLDER: "New folder",
  NEW_NOTE: "New note",
  NOTICE_DRAG_LOCKED: "File drag-and-drop is now Locked",
  NOTICE_DRAG_UNLOCKED: "File drag-and-drop is now Unlocked",
  NOTICE_IMAGES_HIDDEN: "Image folders are now Hidden",
  NOTICE_IMAGES_VISIBLE: "Image folders are now Visible",
  NOTICE_DRAG_LOCKED_WARN: "File drag-and-drop is locked by ToolkitPlugin."
};

// src/i18n/locales/zh.ts
var zh_default = {
  HIDE_IMAGE_FOLDERS_NAME: "\u9690\u85CF\u56FE\u7247\u6587\u4EF6\u5939",
  HIDE_IMAGE_FOLDERS_DESC: "\u9690\u85CF\u4EC5\u5305\u542B\u56FE\u7247\u7684\u6587\u4EF6\u5939\uFF0C\u4FDD\u6301\u6587\u4EF6\u5217\u8868\u6574\u6D01\u3002",
  QUICK_CREATE_FOLDER_NAME: "\u663E\u793A\u5FEB\u901F\u65B0\u5EFA\u6587\u4EF6\u5939\u6309\u94AE",
  QUICK_CREATE_FOLDER_DESC: "\u5728\u6587\u4EF6\u5939\u65C1\u6DFB\u52A0\u56FE\u6807\uFF0C\u4EE5\u4FBF\u5FEB\u901F\u521B\u5EFA\u5B50\u6587\u4EF6\u5939\u3002",
  LOCK_DRAG_NAME: "\u9501\u5B9A\u6587\u4EF6\u62D6\u62FD",
  LOCK_DRAG_DESC: "\u9632\u6B62\u5728\u6587\u4EF6\u5217\u8868\u91CC\u8BEF\u64CD\u4F5C\u79FB\u52A8\u6587\u4EF6\u6216\u6587\u4EF6\u5939\u3002",
  SCALE_MERMAID_NAME: "\u542F\u7528 Mermaid \u7F29\u653E\u4E0E\u5168\u5C4F",
  SCALE_MERMAID_DESC: "\u81EA\u52A8\u8BA9 Mermaid \u56FE\u8868\u9002\u914D\u7B14\u8BB0\u5BBD\u5EA6\uFF0C\u5E76\u542F\u7528\u60AC\u505C\u7F29\u653E\u4E0E\u5168\u5C4F\u67E5\u770B\u3002",
  MERMAID_SENSITIVITY_NAME: "Mermaid \u7F29\u653E\u7075\u654F\u5EA6",
  MERMAID_SENSITIVITY_DESC: "\u8C03\u8282\u6EDA\u8F6E/\u624B\u52BF\u7F29\u653E Mermaid \u56FE\u8868\u7684\u901F\u5EA6\uFF08\u9ED8\u8BA4 1.0\uFF09\u3002",
  AUTO_OPEN_WOLAI_NAME: "\u81EA\u52A8\u6253\u5F00 Wolai \u98CE\u683C\u6587\u4EF6\u5939",
  AUTO_OPEN_WOLAI_DESC: "\u70B9\u51FB\u4EC5\u5305\u542B\u4E00\u4E2A\u540C\u540D MD \u6587\u4EF6\u7684\u6587\u4EF6\u5939\u65F6\uFF0C\u81EA\u52A8\u6253\u5F00\u8BE5\u6587\u4EF6\u3002",
  QUICK_CREATE_NOTE_NAME: "\u663E\u793A\u5FEB\u901F\u65B0\u5EFA\u7B14\u8BB0\u6309\u94AE",
  QUICK_CREATE_NOTE_DESC: '\u5728\u6587\u4EF6\u5939\u65C1\u663E\u793A "+" \u56FE\u6807\uFF0C\u4EE5\u4FBF\u5FEB\u901F\u521B\u5EFA\u65B0\u7B14\u8BB0\u3002',
  AUTO_DETECT_LANG_NAME: "\u81EA\u52A8\u8BC6\u522B\u4EE3\u7801\u8BED\u8A00",
  AUTO_DETECT_LANG_DESC: "\u5411\u7A7A\u767D\u4EE3\u7801\u5757\u7C98\u8D34\u4EE3\u7801\u65F6\uFF0C\u81EA\u52A8\u8BC6\u522B\u5E76\u586B\u5145\u8BED\u8A00\u6807\u8BC6\u7B26\u3002",
  AUTO_FOCUS_BLOCK_NAME: "\u81EA\u52A8\u5B9A\u4F4D\u5149\u6807\u81F3\u4EE3\u7801\u5757\u5185",
  AUTO_FOCUS_BLOCK_DESC: "\u5F53\u63D2\u5165\u7A7A\u767D\u4EE3\u7801\u5757\u7ED3\u6784\u65F6\uFF0C\u81EA\u52A8\u5C06\u5149\u6807\u79FB\u52A8\u5230\u4EE3\u7801\u5757\u5185\u90E8\u3002",
  COMMAND_TOGGLE_DRAG: "\u5207\u6362\u6587\u4EF6\u8D44\u6E90\u7BA1\u7406\u5668\u62D6\u62FD\u9501\u5B9A\u72B6\u6001",
  COMMAND_TOGGLE_IMAGES: "\u5207\u6362\u56FE\u7247\u6587\u4EF6\u5939\u663E\u793A\u72B6\u6001",
  RIBBON_TOGGLE_IMAGES: "\u5207\u6362\u56FE\u7247\u6587\u4EF6\u5939\u663E\u793A",
  RIBBON_TOGGLE_DRAG: "\u5207\u6362\u62D6\u62FD\u9501\u5B9A",
  MERMAID_ZOOM_IN: "\u653E\u5927",
  MERMAID_ZOOM_OUT: "\u7F29\u5C0F",
  MERMAID_RESET: "\u91CD\u7F6E\u7F29\u653E",
  MERMAID_FULLSCREEN: "\u5168\u5C4F\u67E5\u770B",
  MERMAID_MODAL_TITLE: "Mermaid \u6D41\u7A0B\u56FE\u67E5\u770B\u5668",
  NEW_FOLDER: "\u65B0\u5EFA\u6587\u4EF6\u5939",
  NEW_NOTE: "\u65B0\u5EFA\u7B14\u8BB0",
  NOTICE_DRAG_LOCKED: "\u6587\u4EF6\u62D6\u62FD\u529F\u80FD\u5DF2\u9501\u5B9A",
  NOTICE_DRAG_UNLOCKED: "\u6587\u4EF6\u62D6\u62FD\u529F\u80FD\u5DF2\u89E3\u9501",
  NOTICE_IMAGES_HIDDEN: "\u56FE\u7247\u6587\u4EF6\u5939\u5DF2\u9690\u85CF",
  NOTICE_IMAGES_VISIBLE: "\u56FE\u7247\u6587\u4EF6\u5939\u5DF2\u663E\u793A",
  NOTICE_DRAG_LOCKED_WARN: "\u6587\u4EF6\u62D6\u62FD\u5DF2\u88AB ToolkitPlugin \u9501\u5B9A\u3002"
};

// src/i18n/index.ts
var currentLocale = import_obsidian.moment.locale();
var localeMap = {
  en: en_default,
  zh: zh_default,
  "zh-cn": zh_default,
  "zh-hk": zh_default,
  "zh-tw": zh_default
};
var locale = localeMap[currentLocale] || en_default;
function t(str) {
  return locale[str] || en_default[str];
}

// src/main.ts
var DEFAULT_SETTINGS = {
  isHidden: true,
  autoOpenWolaiFolders: true,
  showQuickCreateButton: true,
  showQuickCreateFolderButton: true,
  lockDragAndDrop: false,
  autoDetectLanguage: true,
  autoFocusCodeBlock: true,
  scaleMermaid: true,
  mermaidZoomSensitivity: 1
};
var ToolkitPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.lockRibbonEl = null;
  }
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.addRibbonIcon("image-off", t("RIBBON_TOGGLE_IMAGES"), (evt) => {
        this.toggleVisibility();
      });
      this.lockRibbonEl = this.addRibbonIcon(this.settings.lockDragAndDrop ? "lock" : "unlock", t("RIBBON_TOGGLE_DRAG"), (evt) => {
        this.toggleDragLock();
      });
      this.refreshDragLock();
      this.refreshVisibility();
      this.refreshMermaidScaling();
      this.addCommand({
        id: "toggle-image-folder-visibility",
        name: t("COMMAND_TOGGLE_IMAGES"),
        callback: () => {
          this.toggleVisibility();
        }
      });
      this.addCommand({
        id: "toggle-drag-lock",
        name: t("COMMAND_TOGGLE_DRAG"),
        callback: () => {
          this.toggleDragLock();
        }
      });
      this.registerDomEvent(document, "dragstart", (evt) => {
        if (this.settings.lockDragAndDrop) {
          const target = evt.target;
          if (target.closest(".nav-file") || target.closest(".nav-folder")) {
            evt.preventDefault();
            new import_obsidian2.Notice(t("NOTICE_DRAG_LOCKED_WARN"));
          }
        }
      }, true);
      this.addSettingTab(new ToolkitSettingTab(this.app, this));
      this.refreshVisibility();
      this.registerDomEvent(document, "click", (evt) => {
        if (!this.settings.autoOpenWolaiFolders)
          return;
        const target = evt.target;
        if (target.closest(".toolkit-icons-container") || target.closest(".toolkit-action-icon"))
          return;
        if (target.classList.contains("nav-folder-collapse-indicator") || target.closest(".nav-folder-collapse-indicator")) {
          return;
        }
        const folderTitleEl = target.closest(".nav-folder-title");
        if (folderTitleEl) {
          const path = folderTitleEl.getAttr("data-path");
          if (!path)
            return;
          const folder = this.app.vault.getAbstractFileByPath(path);
          if (folder instanceof import_obsidian2.TFolder) {
            this.handleFolderClick(folder);
          }
        }
      });
      this.registerInterval(window.setInterval(() => this.injectCreateButtons(), 1e3));
      this.registerInterval(window.setInterval(() => this.injectMermaidZoomControls(), 1e3));
      this.registerEvent(this.app.workspace.on("editor-paste", (evt, editor, view) => {
        var _a;
        if (!this.settings.autoDetectLanguage)
          return;
        const clipboardData = (_a = evt.clipboardData) == null ? void 0 : _a.getData("text/plain");
        if (!clipboardData || clipboardData.length < 5)
          return;
        const cursor = editor.getCursor();
        const lineContent = editor.getLine(cursor.line);
        if (lineContent.trim() === "```") {
          const lang = this.detectLanguage(clipboardData);
          if (lang) {
            editor.setLine(cursor.line, "```" + lang);
          }
          return;
        }
        if (cursor.line > 0) {
          const prevLine = editor.getLine(cursor.line - 1);
          if (prevLine.trim() === "```") {
            const lang = this.detectLanguage(clipboardData);
            if (lang) {
              editor.setLine(cursor.line - 1, "```" + lang);
            }
          }
        }
      }));
      this.registerEvent(this.app.workspace.on("editor-change", (editor) => {
        if (!this.settings.autoFocusCodeBlock)
          return;
        setTimeout(() => {
          const cursor = editor.getCursor();
          const lineCount = editor.lineCount();
          if (cursor.line >= lineCount)
            return;
          const lineContent = editor.getLine(cursor.line);
          if (lineContent.startsWith("```")) {
            if (cursor.line + 2 < lineCount) {
              const nextLine = editor.getLine(cursor.line + 1);
              const afterNextLine = editor.getLine(cursor.line + 2);
              if (nextLine.trim() === "" && afterNextLine.trim() === "```") {
                editor.setCursor({ line: cursor.line + 1, ch: 0 });
              }
            }
          }
        }, 100);
      }));
    });
  }
  detectLanguage(text) {
    const patterns = [
      { lang: "python", regex: /\b(def|class|if|elif|else|for|while|try|except|with|finally)\b.*:\s*$/m },
      { lang: "python", regex: /\bself\.\w+/ },
      { lang: "python", regex: /^\s*#\s+/m },
      { lang: "python", regex: /("""|''')[\s\S]*?\1/ },
      { lang: "python", regex: /^\s*(import|from)\b/m },
      { lang: "javascript", regex: /\b(const|let|var|function|async|await|console\.log|import|export|=>|process\.)\b/ },
      { lang: "typescript", regex: /\b(interface|type|namespace|readonly|private|protected|public|implements|any|as|keyof|unknown)\b/ },
      { lang: "java", regex: /;\s*$/m },
      { lang: "java", regex: /\{\s*$/m },
      { lang: "java", regex: /\b(public|private|protected|static|final|class|interface|package|import|new|void|extends|implements|throws|System\.out\.println)\b/ },
      { lang: "kotlin", regex: /\b(fun|val|var|when|println|data class|companion object|sealed class|lateinit)\b/ },
      { lang: "bash", regex: /^(#!|\s*(echo|sudo|grep|awk|sed|export|ls|cd|mkdir|rm|cp|mv|chmod|chown)\s+)/m },
      { lang: "html", regex: /<\s*(html|head|body|div|span|p|a|script|style|link|meta|!DOCTYPE)\b/i },
      { lang: "css", regex: /^\s*([.#]\w+|[\w-]+)\s*\{|^\s*@\w+|:\s*[\w-]+;/m },
      { lang: "sql", regex: /\b(SELECT|FROM|WHERE|INSERT INTO|UPDATE|DELETE|CREATE TABLE|ALTER TABLE|JOIN|GROUP BY|ORDER BY)\b/i },
      { lang: "dart", regex: /\b(void main\(|Widget build\(|final|Future<\w+>|await|class \w+ extends|@override|setState\(|Scaffold)\b/ }
    ];
    const scores = {};
    for (const p of patterns) {
      const matches = text.match(new RegExp(p.regex, "gi"));
      scores[p.lang] = (scores[p.lang] || 0) + (matches ? matches.length : 0);
    }
    const hasSemicolons = /;\s*$/m.test(text);
    const hasBraces = /\{\s*$/m.test(text);
    if ((hasSemicolons || hasBraces) && scores["python"] > 0) {
      scores["python"] = Math.max(0, scores["python"] - 5);
    }
    if (scores["typescript"] > 0) {
      scores["typescript"] += scores["javascript"];
    }
    let bestLang = null;
    let maxScore = 0;
    for (const lang in scores) {
      if (scores[lang] > maxScore) {
        maxScore = scores[lang];
        bestLang = lang;
      }
    }
    return maxScore >= 1 ? bestLang : null;
  }
  injectCreateButtons() {
    if (!this.settings.showQuickCreateButton && !this.settings.showQuickCreateFolderButton)
      return;
    const folderTitles = document.querySelectorAll(".nav-folder-title:not(.has-toolkit-icons)");
    folderTitles.forEach((el) => {
      const folderTitleEl = el;
      folderTitleEl.addClass("has-toolkit-icons");
      const container = folderTitleEl.createEl("div", { cls: "toolkit-icons-container" });
      if (this.settings.showQuickCreateFolderButton) {
        const folderIconContainer = container.createEl("div", { cls: "toolkit-action-icon toolkit-folder-icon" });
        (0, import_obsidian2.setIcon)(folderIconContainer, "folder-plus");
        folderIconContainer.setAttr("aria-label", t("NEW_FOLDER"));
        this.attachCreateListener(folderIconContainer, folderTitleEl, "folder");
      }
      if (this.settings.showQuickCreateButton) {
        const noteIconContainer = container.createEl("div", { cls: "toolkit-action-icon toolkit-note-icon" });
        (0, import_obsidian2.setIcon)(noteIconContainer, "plus-with-circle");
        noteIconContainer.setAttr("aria-label", t("NEW_NOTE"));
        this.attachCreateListener(noteIconContainer, folderTitleEl, "note");
      }
    });
  }
  attachCreateListener(iconEl, folderTitleEl, type) {
    ["mousedown", "mouseup", "click", "pointerdown", "pointerup"].forEach((eventType) => {
      iconEl.addEventListener(eventType, (evt) => {
        evt.stopPropagation();
        evt.stopImmediatePropagation();
        if (eventType === "mousedown" || eventType === "click")
          evt.preventDefault();
        if (eventType === "mousedown" && evt.button === 0) {
          const path = folderTitleEl.getAttr("data-path");
          if (path) {
            const folder = this.app.vault.getAbstractFileByPath(path);
            if (folder instanceof import_obsidian2.TFolder) {
              if (type === "note") {
                this.handleQuickCreate(folder, path);
              } else {
                this.handleQuickCreateFolder(folder, path);
              }
            }
          }
        }
      }, true);
    });
  }
  handleQuickCreate(folder, path) {
    return __async(this, null, function* () {
      const appAny = this.app;
      try {
        const explorerLeaves = this.app.workspace.getLeavesOfType("file-explorer");
        explorerLeaves.forEach((leaf) => {
          const view = leaf.view;
          if (view.fileItems && view.fileItems[path]) {
            view.fileItems[path].setCollapsed(false);
          }
        });
        const fileManagerAny = this.app.fileManager;
        let newFile;
        if (typeof fileManagerAny.createNewMarkdownFile === "function") {
          newFile = yield fileManagerAny.createNewMarkdownFile(folder);
        } else {
          newFile = yield this.app.vault.create(`${path}/Untitled.md`, "");
        }
        if (newFile) {
          yield this.app.workspace.getLeaf(false).openFile(newFile);
          explorerLeaves.forEach((leaf) => {
            if (leaf.view.revealFile) {
              leaf.view.revealFile(newFile);
            }
          });
        }
      } catch (e) {
        console.error("toolkitPlusin: Quick create failed", e);
      }
    });
  }
  handleQuickCreateFolder(folder, path) {
    return __async(this, null, function* () {
      try {
        const explorerLeaves = this.app.workspace.getLeavesOfType("file-explorer");
        explorerLeaves.forEach((leaf) => {
          const view = leaf.view;
          if (view.fileItems && view.fileItems[path]) {
            view.fileItems[path].setCollapsed(false);
          }
        });
        let newFolderName = "\u672A\u547D\u540D";
        let counter = 1;
        let newFolderPath = `${path}/${newFolderName}`;
        while (this.app.vault.getAbstractFileByPath(newFolderPath)) {
          newFolderName = `\u672A\u547D\u540D ${counter}`;
          newFolderPath = `${path}/${newFolderName}`;
          counter++;
        }
        const newFolder = yield this.app.vault.createFolder(newFolderPath);
        if (newFolder) {
          setTimeout(() => {
            explorerLeaves.forEach((leaf) => {
              const view = leaf.view;
              if (view.revealFile) {
                view.revealFile(newFolder).then(() => {
                  if (view.fileItems && view.fileItems[newFolderPath]) {
                    const folderItem = view.fileItems[newFolderPath];
                    if (folderItem.setRename) {
                      folderItem.setRename(true);
                    } else {
                      const titleEl = folderItem.titleInnerEl;
                      if (titleEl) {
                        const evt = new MouseEvent("click", { detail: 1 });
                        titleEl.dispatchEvent(evt);
                      }
                    }
                  }
                });
              }
            });
          }, 100);
        }
      } catch (e) {
        console.error("toolkitPlusin: Quick create folder failed", e);
      }
    });
  }
  injectMermaidZoomControls() {
    if (!this.settings.scaleMermaid)
      return;
    const mermaidDivs = document.querySelectorAll(".mermaid:not(.has-toolkit-zoom)");
    mermaidDivs.forEach((el) => {
      const mermaidEl = el;
      mermaidEl.addClass("has-toolkit-zoom");
      const controls = mermaidEl.createEl("div", { cls: "toolkit-zoom-controls" });
      const zoomOut = controls.createEl("div", { cls: "toolkit-zoom-icon", attr: { "aria-label": t("MERMAID_ZOOM_OUT") } });
      (0, import_obsidian2.setIcon)(zoomOut, "minus");
      zoomOut.onClickEvent(() => this.updateMermaidZoom(mermaidEl, -0.1));
      const reset = controls.createEl("div", { cls: "toolkit-zoom-icon", attr: { "aria-label": t("MERMAID_RESET") } });
      (0, import_obsidian2.setIcon)(reset, "refresh-ccw");
      reset.onClickEvent(() => this.updateMermaidZoom(mermaidEl, 0, true));
      const zoomIn = controls.createEl("div", { cls: "toolkit-zoom-icon", attr: { "aria-label": t("MERMAID_ZOOM_IN") } });
      (0, import_obsidian2.setIcon)(zoomIn, "plus");
      zoomIn.onClickEvent(() => this.updateMermaidZoom(mermaidEl, 0.1));
      const expand = controls.createEl("div", { cls: "toolkit-zoom-icon", attr: { "aria-label": t("MERMAID_FULLSCREEN") } });
      (0, import_obsidian2.setIcon)(expand, "maximize");
      expand.onClickEvent(() => {
        const svg = mermaidEl.querySelector("svg");
        if (svg) {
          new MermaidModal(this.app, svg.cloneNode(true), this.settings.mermaidZoomSensitivity).open();
        }
      });
      mermaidEl.addEventListener("mouseleave", () => {
        this.updateMermaidZoom(mermaidEl, 0, true);
      });
    });
  }
  updateMermaidZoom(el, delta, reset = false) {
    const svg = el.querySelector("svg");
    if (!svg)
      return;
    let currentScale = parseFloat(el.getAttr("data-zoom") || "1.0");
    if (reset) {
      currentScale = 1;
    } else {
      currentScale = Math.max(0.1, Math.min(5, currentScale + delta));
    }
    el.setAttr("data-zoom", currentScale.toString());
    svg.style.transform = `scale(${currentScale})`;
    svg.style.transformOrigin = "top center";
    if (currentScale > 1) {
      el.style.overflowX = "auto";
    } else {
      el.style.overflowX = "hidden";
    }
  }
  handleFolderClick(folder) {
    return __async(this, null, function* () {
      const children = folder.children.filter((child) => {
        if (child instanceof import_obsidian2.TFolder && child.name.toLowerCase() === "image")
          return false;
        return true;
      });
      const mdFiles = children.filter((child) => child instanceof import_obsidian2.TFile && child.extension === "md");
      if (mdFiles.length === 1) {
        const file = mdFiles[0];
        const leaf = this.app.workspace.getLeaf(false);
        leaf.openFile(file);
      }
    });
  }
  toggleDragLock() {
    return __async(this, null, function* () {
      this.settings.lockDragAndDrop = !this.settings.lockDragAndDrop;
      yield this.saveSettings();
      this.refreshDragLock();
      const status = this.settings.lockDragAndDrop ? t("NOTICE_DRAG_LOCKED") : t("NOTICE_DRAG_UNLOCKED");
      new import_obsidian2.Notice(status);
    });
  }
  refreshDragLock() {
    if (this.lockRibbonEl) {
      (0, import_obsidian2.setIcon)(this.lockRibbonEl, this.settings.lockDragAndDrop ? "lock" : "unlock");
    }
    if (this.settings.lockDragAndDrop) {
      document.body.classList.add("is-drag-locked");
    } else {
      document.body.classList.remove("is-drag-locked");
    }
  }
  toggleVisibility() {
    return __async(this, null, function* () {
      this.settings.isHidden = !this.settings.isHidden;
      yield this.saveSettings();
      this.refreshVisibility();
      const status = this.settings.isHidden ? t("NOTICE_IMAGES_HIDDEN") : t("NOTICE_IMAGES_VISIBLE");
      new import_obsidian2.Notice(status);
    });
  }
  refreshVisibility() {
    if (this.settings.isHidden) {
      document.body.classList.add("hide-image-folder");
    } else {
      document.body.classList.remove("hide-image-folder");
    }
  }
  refreshMermaidScaling() {
    if (this.settings.scaleMermaid) {
      document.body.classList.add("toolkit-scale-mermaid");
    } else {
      document.body.classList.remove("toolkit-scale-mermaid");
    }
  }
  onunload() {
    document.body.classList.remove("hide-image-folder", "is-drag-locked", "toolkit-scale-mermaid");
    document.querySelectorAll(".toolkit-icons-container").forEach((el) => el.remove());
    document.querySelectorAll(".has-toolkit-icons").forEach((el) => el.classList.remove("has-toolkit-icons"));
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, yield this.loadData());
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
};
var MermaidModal = class extends import_obsidian2.Modal {
  constructor(app, svg, sensitivity) {
    super(app);
    this.svg = svg;
    this.sensitivity = sensitivity;
    this.scale = 1;
    this.x = 0;
    this.y = 0;
    this.isDragging = false;
    this.startX = 0;
    this.startY = 0;
  }
  onOpen() {
    const { contentEl } = this;
    this.titleEl.setText(t("MERMAID_MODAL_TITLE"));
    contentEl.addClass("toolkit-mermaid-modal-content");
    this.svg.removeAttribute("width");
    this.svg.removeAttribute("height");
    this.svg.style.transform = "none";
    this.svg.style.maxWidth = "none";
    this.svg.style.width = "auto";
    this.svg.style.height = "auto";
    this.svg.style.transformOrigin = "center center";
    this.container = contentEl.createEl("div", { cls: "toolkit-mermaid-modal-container" });
    this.container.appendChild(this.svg);
    this.setupInteraction();
  }
  setupInteraction() {
    this.container.addEventListener("wheel", (e) => {
      e.preventDefault();
      const delta = -e.deltaY;
      const speed = 1e-3 * this.sensitivity;
      const factor = Math.exp(delta * speed);
      const newScale = this.scale * factor;
      this.scale = Math.max(0.1, Math.min(20, newScale));
      this.updateTransform();
    }, { passive: false });
    this.container.addEventListener("pointerdown", (e) => {
      this.isDragging = true;
      this.startX = e.clientX - this.x;
      this.startY = e.clientY - this.y;
      this.container.setPointerCapture(e.pointerId);
      this.container.addClass("is-grabbing");
    });
    this.container.addEventListener("pointermove", (e) => {
      if (!this.isDragging)
        return;
      this.x = e.clientX - this.startX;
      this.y = e.clientY - this.startY;
      this.updateTransform();
    });
    this.container.addEventListener("pointerup", (e) => {
      this.isDragging = false;
      this.container.releasePointerCapture(e.pointerId);
      this.container.removeClass("is-grabbing");
    });
  }
  updateTransform() {
    if (this.svg) {
      this.svg.style.transform = `translate(${this.x}px, ${this.y}px) scale(${this.scale})`;
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var ToolkitSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Toolkit Plugin Settings" });
    new import_obsidian2.Setting(containerEl).setName(t("HIDE_IMAGE_FOLDERS_NAME")).setDesc(t("HIDE_IMAGE_FOLDERS_DESC")).addToggle((toggle) => toggle.setValue(this.plugin.settings.isHidden).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.isHidden = value;
      yield this.plugin.saveSettings();
      this.plugin.refreshVisibility();
    })));
    new import_obsidian2.Setting(containerEl).setName(t("AUTO_OPEN_WOLAI_NAME")).setDesc(t("AUTO_OPEN_WOLAI_DESC")).addToggle((toggle) => toggle.setValue(this.plugin.settings.autoOpenWolaiFolders).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.autoOpenWolaiFolders = value;
      yield this.plugin.saveSettings();
    })));
    new import_obsidian2.Setting(containerEl).setName(t("QUICK_CREATE_NOTE_NAME")).setDesc(t("QUICK_CREATE_NOTE_DESC")).addToggle((toggle) => toggle.setValue(this.plugin.settings.showQuickCreateButton).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.showQuickCreateButton = value;
      yield this.plugin.saveSettings();
      document.querySelectorAll(".toolkit-icons-container").forEach((el) => el.remove());
      document.querySelectorAll(".has-toolkit-icons").forEach((el) => el.classList.remove("has-toolkit-icons"));
      this.plugin.injectCreateButtons();
    })));
    new import_obsidian2.Setting(containerEl).setName(t("QUICK_CREATE_FOLDER_NAME")).setDesc(t("QUICK_CREATE_FOLDER_DESC")).addToggle((toggle) => toggle.setValue(this.plugin.settings.showQuickCreateFolderButton).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.showQuickCreateFolderButton = value;
      yield this.plugin.saveSettings();
      document.querySelectorAll(".toolkit-icons-container").forEach((el) => el.remove());
      document.querySelectorAll(".has-toolkit-icons").forEach((el) => el.classList.remove("has-toolkit-icons"));
      this.plugin.injectCreateButtons();
    })));
    new import_obsidian2.Setting(containerEl).setName(t("LOCK_DRAG_NAME")).setDesc(t("LOCK_DRAG_DESC")).addToggle((toggle) => toggle.setValue(this.plugin.settings.lockDragAndDrop).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.lockDragAndDrop = value;
      yield this.plugin.saveSettings();
      this.plugin.refreshDragLock();
    })));
    new import_obsidian2.Setting(containerEl).setName(t("SCALE_MERMAID_NAME")).setDesc(t("SCALE_MERMAID_DESC")).addToggle((toggle) => toggle.setValue(this.plugin.settings.scaleMermaid).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.scaleMermaid = value;
      yield this.plugin.saveSettings();
      this.plugin.refreshMermaidScaling();
    })));
    new import_obsidian2.Setting(containerEl).setName(t("AUTO_FOCUS_BLOCK_NAME")).setDesc(t("AUTO_FOCUS_BLOCK_DESC")).addToggle((toggle) => toggle.setValue(this.plugin.settings.autoFocusCodeBlock).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.autoFocusCodeBlock = value;
      yield this.plugin.saveSettings();
    })));
    new import_obsidian2.Setting(containerEl).setName(t("AUTO_DETECT_LANG_NAME")).setDesc(t("AUTO_DETECT_LANG_DESC")).addToggle((toggle) => toggle.setValue(this.plugin.settings.autoDetectLanguage).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.autoDetectLanguage = value;
      yield this.plugin.saveSettings();
    })));
    new import_obsidian2.Setting(containerEl).setName(t("MERMAID_SENSITIVITY_NAME")).setDesc(t("MERMAID_SENSITIVITY_DESC")).addSlider((slider) => slider.setLimits(0.1, 2, 0.1).setValue(this.plugin.settings.mermaidZoomSensitivity).setDynamicTooltip().onChange((value) => __async(this, null, function* () {
      this.plugin.settings.mermaidZoomSensitivity = value;
      yield this.plugin.saveSettings();
    })));
  }
};
